### ISSUE TITLE
traceback thrown during "install reqs for virtualenv(changelog)

### ISSUE THREAD

**Issue by nicholasmhughes** [s0undt3ch/python-tools-scripts#40]
* new virtualenv using pyenv and python 3.10.11
* currently using version 0.15.0 of python-tools-scripts
* pip install pre-commit nox
* pre-commit run

also tried 0.17.0 with the same result. am I missing a step somewhere, or is there a bug?

```
Check Changelog Entries..................................................Failed
- hook id: tools
- exit code: 1

[10:25:15] Install requirements for virtualenv(changelog) ...                   
Traceback (most recent call last):
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/bin/tools", line 8, in <module>
    sys.exit(main())
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/__main__.py", line 26, in main
    parser.parse_args()
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/parser.py", line 486, in parse_args
    options.func(options)
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/parser.py", line 728, in __call__
    with venv:
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/virtualenv.py", line 228, in __enter__
    self._install_requirements()
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/virtualenv.py", line 155, in _install_requirements
    self.install(*self.pip_args, *requirements)
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/virtualenv.py", line 242, in install
    return self.run(self.venv_python, "-m", "pip", "install", *args, **kwargs)
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/virtualenv.py", line 263, in run
    return self.ctx._run(*args, env=environ, **kwargs)
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/parser.py", line 174, in _run
    return process.run(
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/process.py", line 264, in run
    loop.run_until_complete(
  File "/home/nmhughes/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/process.py", line 219, in _subprocess_run
    proc = await _create_subprocess_exec(
  File "/home/nmhughes/.cache/pre-commit/repoe7cj61oz/py_env-python3/lib/python3.10/site-packages/ptscripts/process.py", line 171, in _create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/home/nmhughes/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/home/nmhughes/.pyenv/versions/3.10.11/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/home/nmhughes/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/home/nmhughes/.pyenv/versions/3.10.11/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/home/nmhughes/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/nmhughes/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python')
```

**Comment by s0undt3ch** [comment]
> yup.
> 
> ```
> ls -l /home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python3
> lrwxrwxrwx 1 nmhughes nmhughes 6 Mar 28 12:58 /home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python3 -> python
> ```

Wait, so `/home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python` also exists, right?

**Comment by nicholasmhughes** [comment]
yup.

```
s /home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/
activate  activate.csh  activate.fish  activate.nu  activate.ps1  activate_this.py  pip  pip3  pip3.10  python  python3  python3.10  towncrier  wheel  wheel3  wheel-3.10  wheel3.10
```

**Comment by s0undt3ch** [comment]
Hmm, do you have `virtualenv` in path?

I'm trying to figure out if the virtual environment was created with `virtualenv` or python's `venv` module

**Comment by nicholasmhughes** [comment]
oh... interesting...

```
ls -l /home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python
lrwxrwxrwx 1 nmhughes nmhughes 19 Mar 28 12:58 /home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python -> /usr/bin/python3.10
```

```
ls -l /usr/bin/python3.10
ls: cannot access '/usr/bin/python3.10': No such file or directory
```

**Comment by nicholasmhughes** [comment]
created the venv with

```
pyenv virtualenv salt
```

**Comment by s0undt3ch** [comment]
Ok, so this is a nested virtualenv...
What platform are you in?

**Comment by s0undt3ch** [comment]
nevermind `/usr/...`, so, linux

**Comment by nicholasmhughes** [comment]
yeah... Manjaro

**Comment by nicholasmhughes** [comment]
hmmm... possibly. can I just wipe out the `.tools-venv` directory and have it recreated?

**Comment by s0undt3ch** [comment]
> hmmm... possibly. can I just wipe out the `.tools-venv` directory and have it recreated?

yes, you can nuke that directory and it'll get recreated.

**Comment by nicholasmhughes** [comment]
that did it. I must've had some cruft stuck in there from a pre-commit run prior to getting pyenv "right". I did a `pre-commit clean` a bunch of times while I was troubleshooting, but it didn't really occur to me to clean `.tools-venv`. Is there any automated way to catch this scenario and rebuild the dir... or do we have to manually wipe it and re-run like I did?

```
ls -l /home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python
lrwxrwxrwx 1 nmhughes nmhughes 53 Jul  6 11:52 /home/nmhughes/dev/salt-projects/salt/.tools-venvs/changelog/bin/python -> /home/nmhughes/.pyenv/versions/3.10.11/bin/python3.10


ls -l /home/nmhughes/.pyenv/versions/3.10.11/bin/python3.10
-rwxr-xr-x 1 nmhughes nmhughes 17024 Jul  5 11:18 /home/nmhughes/.pyenv/versions/3.10.11/bin/python3.10
```

**Comment by s0undt3ch** [comment]
So, if the requirements change, the virtualenv in `.tools-venv` will get re-created, catching "things like this" might be a little harder to automate... But I'm open to suggestions(and PR's :grin:)
